// Create web server
// Load Express module
var express = require('express');
var app = express();
// Load body-parser module
var bodyParser = require('body-parser');
// Load path module
var path = require('path');
// Load fs module
var fs = require('fs');
